### ISSUE TITLE
Values pasted into text fields are duplicated

### ISSUE THREAD

**Issue by mipastgt** [gluonhq/scenebuilder#306] opened 2020-12-18 15:04 UTC
If you paste a value into the, e.g., "On Drag Detected" field it will get duplicated. I.e., if you copy something like "doIt" from somewhere and past it into the said field, you will end up with "doItdoIt" in that field. I tested this on a macBook Pro with SceneBuilder 15 RC1. (Actually this is not a new bug because it can be observed in older versions too.)

**Comment by jperedadnr** [comment] 2020-12-18 16:19
Duplicate of #221, see issue for some explanation (JavaFX issue).
Also #263, with some hack to prevent it within SB.

**Closed by jperedadnr** 2020-12-18 16:19 UTC

**Comment by mipastgt** [comment] 2020-12-18 17:55
Has this issue ever been moved to the JBS so that it gets a chance to be fixed? I couldn't find it there.

**Comment by Oliver-Loeffler** [comment] 2022-01-04 23:52
As the issue has not been solved yet in JavaFX directly, how about adding a work around to Scene Builder?
Would this be acceptable? At this moment, the pasting issue is quite annoying and this kind of seriously impacts usability of SB.
