### ISSUE TITLE
using TabPane from JFoenix crashes Scene Builder

### ISSUE THREAD

**Issue by seriouslyEnter** [gluonhq/scenebuilder#183] opened 2018-06-02 00:12 UTC
Product Version
JavaFX Scene Builder 8.4.1

Build Information
Version 8.4.1
Date: 2017-10-17
Java Version: 1.8.0_144-b01, Oracle Corporation

Windows 10, amd64, 10.0

1. added jfoenix-8.0.4.jar (https://github.com/jfoenixadmin/JFoenix).
Also tried repository, makes no difference.
2. used JFXTabPane in an Anchor Pane
3. trying to add a new Tab can lead to crash(unresponsive)
3.1. restart Scene Builder and try adding multiple times until successful
4. selecting any element in the hierarchy View can lead to crash(unresponsive).
For example, selecting the AnchorPane in a Tab. Or adding a Label to a Tab.

I open the fxml file via netbeans to work with.
The behaviour is not consistent.
The crash can occur on any element TabPane, Tab, AnchorPane in Tab.
Also while trying to edit and save changes.
It can take several tries (restarting secene builder) to select an element successfuly to work with.
Tried to find a pattern but couldn't find any, yet.

I have no tried other jfoenix Elements.
I used jfoenix for the first time so I can't report on earlierversions and their behaviour.
No other regular crashes while working with anything else in Scene Builder.

**Comment by seriouslyEnter** [comment] 2018-06-02 20:29
I found a hint while experimenting to to find a pattern.
I usually open fxml files from inside netbeans via the scene builder plugin.
I now tried opening the same fxml file "manually". Starting scene builder and opening the file.
Now I can work whitout any crashes !!!

1. Opening fxml in scene builder via the plugin in netbeans -> crashes scene builder when using JFXTabPane
2. alternative: starting scene builder manually and opening the same fxml file inside scenebuilder -> no crashes while working with JFXTabPane

**Comment by eugener** [comment] 2018-06-02 21:10
Should this issue be closed then?

**Comment by seriouslyEnter** [comment] 2018-06-02 22:53
No, SceneBuilder should not crash on editing fxml file just because it was started from netbeans.

Maybe check if its an issure with SceneBuilder, Netbeans plugin or JFoenix.

**Comment by magician20** [comment] 2018-11-22 10:55
JavaFX Scene Builder 8.5.0

Same problem.

Windows 10 64 bit

**Comment by abhinayagarwal** [comment] 2018-12-07 08:57
I am unable to reproduce this.

NetBeans:

```
Product Version: NetBeans IDE 8.2 (Build 201609300101)
Updates: NetBeans IDE is updated to version NetBeans 8.2 Patch 2
Java: 1.8.0_121; Java HotSpot(TM) 64-Bit Server VM 25.121-b13
Runtime: Java(TM) SE Runtime Environment 1.8.0_121-b13
System: Windows 10 version 10.0 running on amd64; Cp1252; en_IN (nb)
```

Scene Builder:

```
Product Version
JavaFX Scene Builder 8.5.0

Build Information
Version 8.5.0
Date: 2018-06-05
Java Version: 1.8.0_171-b11, Oracle Corporation
```

FXML used to open Scene Builder from NetBeans:

```
<?xml version="1.0" encoding="UTF-8"?>

<?import java.lang.*?>
<?import java.util.*?>
<?import javafx.scene.*?>
<?import javafx.scene.control.*?>
<?import javafx.scene.layout.*?>
<?import com.jfoenix.controls.JFXTabPane?>

<AnchorPane id="AnchorPane" prefHeight="200" prefWidth="320" xmlns:fx="http://javafx.com/fxml/1" fx:controller="javafxapplication.FXMLDocumentController">
    <children>
        <JFXTabPane fx:id="tabPane"/>
    </children>
</AnchorPane>
```

@seriouslyEnter  @magician20 Can anyone of you provide more information on how to reproduce this issue?

**Comment by jperedadnr** [comment] 2019-05-02 16:49
I can't reproduce the issue (crash/freeze). 

However I see a NPE in the console: When adding a built-in `Tab` to either a `TabPane`or a `JFXTabPane`, Scene Builder throws a NPE at

At `com.oracle.javafx.scenebuilder.kit.editor.panel.content.ContentPanelController::reveal`:
```
final Tab tab = (Tab) sceneGraphObject;
final TabPane tabPane = tab.getTabPane();
tabPane.getSelectionModel().select(tab);
```

I'll close this issue and open a follow up issue with this NPE

**Closed by jperedadnr** 2019-05-02 16:49 UTC
Labels: bug, custom control

**Comment by KenobySky** [comment] 2019-11-09 15:15
Im having the same issue. When Opening it from apache netbeans 11.2 it does hang up at random times. 
Very annoying.

**Comment by KenobySky** [comment] 2019-11-09 15:15
Is there anything I can do to generate a log to help you guys solve it?

**Comment by aidanwd** [comment] 2020-07-05 19:46
> 
> 
> I found a hint while experimenting to to find a pattern.
> I usually open fxml files from inside netbeans via the scene builder plugin.
> I now tried opening the same fxml file "manually". Starting scene builder and opening the file.
> Now I can work whitout any crashes !!!
> 
>     1. Opening fxml in scene builder via the plugin in netbeans -> crashes scene builder when using JFXTabPane
> 
>     2. alternative: starting scene builder manually and opening the same fxml file inside scenebuilder -> no crashes while working with JFXTabPane

Thanks for the help my man!
