### ISSUE TITLE
SceneBuilder 10.0.0 crashes on OSX when regaining focus

### ISSUE THREAD

**Issue by odbuser2** [gluonhq/scenebuilder#184] opened 2018-06-10 02:00 UTC
**Description**
SceneBuilder crashes when regaining focus

**To reproduce**
Launch SceneBuilder.
Close the initial dialog or select Empty.
Click on the desktop (cause SceneBuilder to lose focus)
Click on the SceneBuilder again.
SceneBuilder crashes.

**Detail**
```
Product Version
JavaFX Scene Builder 10.0.0

Build Information
Version 10.0.0
Date: 2018-06-05
Java Version: 10.0.1+10, Oracle Corporation

Java
10.0.1+10, Oracle Corporation

Operating System
Mac OS X, x86_64, 10.13.5

Copyright (c) 2015-2018, Gluon.
```

**Comment by odbuser2** [comment] 2018-06-13 04:00
The executable jar with Java Version: 10.0.1+10, Oracle Corporation does not have this issue.

So it has to do with the .app in the dmg.  The .app worked on one Macbook Pro and failed on another.  The jar works on both.

**Comment by pfurbacher** [comment] 2019-01-31 22:02
Every version (8, 10, 11) installed from a DMG suffers from this problem. Running the jar, as indicated above, does not exhibit this issue.

**Comment by nemphys** [comment] 2019-03-30 16:02
Any news on this one? The application is pretty much useless if it *always* crashes upon refocus.

**Comment by jperedadnr** [comment] 2019-03-30 17:20
I use frequently Scene Builder on Mac (from the installer), and it works fine for me. I can't reproduce the issue. 
First of all, we'll need to know why it is crashing. 
@nemphys can you post the crash log? Does it happen always or occasionally?

**Comment by nemphys** [comment] 2019-03-30 21:59
Right. I just realised that the crashes were not caused by the application itself; the Lilu+WhateverGreen  kexts I have installed are the culprits (I am fighting a Nvidia problem on external monitors in the latest macOs versions, long story).
Once I disabled them, the crashes disappeared.
Sorry for the false alarm.

**Comment by jperedadnr** [comment] 2019-03-31 11:06
@nemphys Interesting, did you test the zip I posted with your patches applied? If that fails it would imply any Java app installed will fail with the same issue, so the conflict will be probably in the Java native libraries, and not related to the application itself.

**Comment by jperedadnr** [comment] 2019-05-02 15:58
Closing this issue as it can't be reproduced, it can be opened again providing enough details.

**Closed by jperedadnr** 2019-05-02 15:58 UTC
Labels: bug

**Comment by odbuser2** [comment] 2019-05-14 00:46
I haven't experienced the issue on 11 dmg on OSX so far.  I was not doing anything with graphics drivers like @nemphys.  I didn't have any supporting information for the crash.  I didn't see anything tangible in the OSX console.  I will report again if it happens under 11.

Build Information
Version 11.0.0
Date: 2018-11-22
Java Version: 11.0.1+13-LTS, Oracle Corporation

Operating System
Mac OS X, x86_64, 10.14.4
