### ISSUE TITLE
Dialog box bug

### ISSUE THREAD

**Issue by buttonmasher3** [gluonhq/scenebuilder#280] opened 2020-08-08 17:01 UTC
I'm on Ubuntu 20.04 (had the same issue with 19.10) but whenever I try to open Scene Builder from my IDE and there's an error in the fxml file, then sometimes I get really bugged out dialog boxes. I attached a screenshot. That little box in the middle is the dialog box. I have to use the ALT+Tab thumbnail preview to see what the actual dialog message is.
![dialog](https://user-images.githubusercontent.com/68735768/89715926-80b0eb00-d9a9-11ea-9831-3093ee5b886c.png)

**Comment by abhinayagarwal** [comment] 2020-12-24 07:38
Can you please add the FXML file using which the bug can be reproduced?

**Comment by abhinayagarwal** [comment] 2020-12-24 07:43
Seems to be duplicate of #257

**Comment by belu** [comment] 2021-03-06 14:55
@abhinayagarwal 
Had the same issue on Linux with SceneBuilder 11. With SceneBuilder 15 this did not happen again.
So it seems this issue can be closed.

@buttonmasher3 Have you tried it with SceneBuilder 15?

**Comment by abhinayagarwal** [comment] 2021-03-06 18:05
Yes, this was fixed in JavaFX 13 as a part of [JDK-8193502](https://bugs.openjdk.java.net/browse/JDK-8193502). SB 15 and later will have this fix.

**Closed by abhinayagarwal** 2021-03-06 18:05 UTC
