### ISSUE TITLE
Does not start after installation on Windows 10

### ISSUE THREAD

**Issue by tapaniantonrundgren** [gluonhq/scenebuilder#344] opened 2021-03-31 11:22 UTC
SceneBuilder does not start on Windows 10 Enterprise 20H2

### Expected Behavior
Should start when selected from Start Menu

### Current Behavior
I can find the scenebuilder.exe process in Task Manager, but no display

### Steps to Reproduce
Try to start SceneBuilder from installed icon from Start Menu or from filesystem

### Your Environment
Windows 10 Enterprise 20H2
$ java --version
java 16 2021-03-16
Java(TM) SE Runtime Environment (build 16+36-2231)
Java HotSpot(TM) 64-Bit Server VM (build 16+36-2231, mixed mode, sharing)

### Screenshots
If started from git-bash -> exception as follows:
$ ./SceneBuilder.exe
Exception in thread "WindowsNativeRunloopThread" java.lang.NoSuchMethodError: <init>
        at javafx.graphics/com.sun.glass.ui.win.WinApplication.staticScreen_getScreens(Native Method)
        at javafx.graphics/com.sun.glass.ui.Screen.initScreens(Unknown Source)
        at javafx.graphics/com.sun.glass.ui.Application.lambda$run$1(Unknown Source)
        at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException: Cannot invoke "com.sun.glass.ui.Screen.getNativeScreen()" because "<parameter1>" is null
        at javafx.graphics/com.sun.prism.d3d.D3DPipeline.getAdapterOrdinal(Unknown Source)
        at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.assignScreensAdapters(Unknown Source)
        at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.runToolkit(Unknown Source)
        at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.lambda$startup$10(Unknown Source)
        at javafx.graphics/com.sun.glass.ui.Application.lambda$run$1(Unknown Source)
        at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)

**Comment by Oliver-Loeffler** [comment] 2021-03-31 16:34
Just ran a quick test.

# Environment:
* Windows Edition: Windows 10 Pro
* Version: 20H2
* Build: 19042.867
* Performance: Windows Feature Experience Pack 120.2212.551.0

# JDK runtime image provided by SceneBuilder 

```
$ pwd
/c/Users/oliver/AppData/Local/SceneBuilder16/runtime/bin
$ ./java.exe --version
openjdk 16 2021-03-16
OpenJDK Runtime Environment AdoptOpenJDK (build 16+36)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 16+36, mixed mode)

```

# SceneBuilder version info

See in (`Help Menu/About Scene Builder`).

```
Product Version
JavaFX Scene Builder 16.0.0

Build Information
Version 16.0.0
Date: 2021-03-26 18:43:14
JavaFX Version: 16
Java Version: 16+36, AdoptOpenJDK

Logging
The default configuration stores logging output in a file named scenebuilder-16.0.0.log (possibly followed by a trailing '.' and a digit).
The default file path is C:\Users\Oliver\AppData\Local\Temp\scenebuilder-16.0.0.log

JavaFX
16

Java
16+36, AdoptOpenJDK

Operating System
Windows 10, amd64, 10.0
```

Also tested from GitBash:

```
$ git --version
git version 2.30.1.windows.1
```

Got following response:

```
$ ./SceneBuilder.exe
Mar 31, 2021 6:23:14 PM com.oracle.javafx.scenebuilder.app.SceneBuilderApp logTimestamp
INFORMATION: JavaFX Scene Builder started
```

# Questions

* Are there multiple screens?
* Do the multiple screens have same or different resolutions?
* Is there something active like Eyefinity or NvSurround View?
* Can you please also share your operating system build?
*  Is it possible that you could share the logfile created? 


Thanks!

**Comment by Oliver-Loeffler** [comment] 2021-04-02 13:36
Hi @tapaniantonrundgren !

I'm still playing around with that but have not had success yet in reproducing the issue.
Would be able to answer some of the following questions? This hopefully may help to get a trace of whats happening.

* Do you have multiple display adapters running (e.g. CPU graphics + external graphics adpter) etc.?
* Are there multiple screens?
* Do the multiple screens have same or different resolutions?
* Is there something active like Eyefinity or NvSurround View?
* Which operating system build are you using?
* Is it possible that you could share the logfile created? 
* What's the systems locale (country setting and language)?

Thanks!

**Comment by tapaniantonrundgren** [comment] 2021-04-06 07:12
I use large monitor (laptop in docking station), that could be the reason. Will test with laptop only later today

**Comment by tapaniantonrundgren** [comment] 2021-04-06 12:05
No, that was not the problem (not using laptop display but a separate monitor). After removing RedHat OpenJDK 1.8.0_282 it starts as expected!

**Comment by abhinayagarwal** [comment] 2021-04-07 17:51
@Oliver-Loeffler  The proper fix for this issue would be to version the native libs (`glass.dll`)  on Windows. The issue is already logged in the [JBS](https://bugs.openjdk.java.net/browse/JDK-8223746). More information on this can be found here: https://github.com/karakun/OpenWebStart/issues/125#issuecomment-644740176

PDFSAM fixed it by [setting the PATH in the launcher script to its own runtime](https://github.com/torakiki/pdfsam/commit/db365ad8ad07be40d7561928f74487478365d2de). We could try something like this, however, I need to figure if its really possible in `jpackage`.

**Comment by Oliver-Loeffler** [comment] 2021-04-08 19:28
I have an idea to achieve this with `jpackage` but first I have to be able to reproduce it locally.

**Comment by abhinayagarwal** [comment] 2021-04-10 10:41
@Oliver-Loeffler A package can be created and someone who has the issue can test it for you.

**Comment by tapaniantonrundgren** [comment] 2021-04-14 10:36
Great! Now it starts on my Windows 10 too!

**Comment by Oliver-Loeffler** [comment] 2021-04-14 20:29
Well, I was now able to reproduce the issue. It indeed happens, when a JDK8 with JavaFX has been installed and its `JRE\lib` directory has been added to the envrionment path. 

```
C:\Users\Oliver\AppData\Local\SceneBuilder\runtime\bin>java.exe -XshowSettings
VM settings:
    Max. Heap Size (Estimated): 29.97G
    Using VM: OpenJDK 64-Bit Server VM

Property settings:
    file.encoding = Cp1252
    file.separator = \
    java.class.path =
    java.class.version = 60.0
    java.home = C:\Users\Oliver\AppData\Local\SceneBuilder\runtime
    java.io.tmpdir = C:\Users\Oliver\AppData\Local\Temp\
    java.library.path = C:\Users\Oliver\AppData\Local\SceneBuilder\runtime\bin
        C:\WINDOWS\Sun\Java\bin
        C:\WINDOWS\system32
        C:\WINDOWS
        C:\Program Files\Java\jdk8u192-b12-with-jfx8u202-b02\jre\bin
        C:\Python39\Scripts\
        C:\Python39\
        C:\Program Files\AdoptOpenJDK\jdk-16.0.0.36-hotspot\bin
```

The directory `C:\Program Files\Java\jdk8u192-b12-with-jfx8u202-b02\jre\bin` contains a copy of  `glass.dll`. Indeed, after removing `glass.dll` from ` C:\Program Files\Java\jdk8u192-b12-with-jfx8u202-b02\jre\bin` SceneBuilder will start but does not look as expected. The program remains unusable.

![SceneBuilderIssue](https://user-images.githubusercontent.com/22102800/114774722-c0b64200-9d70-11eb-8ef9-587bb67e0b6a.png)

**Closed** 2021-05-25 05:57 UTC
Labels: bug

**Comment by Oliver-Loeffler** [comment] 2021-08-04 16:08
Finally @palexdev tested this in #354.
