### ISSUE TITLE
Scene Builder is setting "id" not "fx:id" in XML

### ISSUE THREAD

**Issue by mikehearn** [gluonhq/scenebuilder#215] opened 2019-01-05 12:28 UTC
FXML generated by the latest Scene Builder seems wrong in a subtle way - the id attribute needs to be "fx:id" for it to be recognised by FXMLLoader in Java 8 but it's being generated as just "id", which doesn't work.

**Comment by abhinayagarwal** [comment] 2019-01-31 10:44
I cannot reproduce this from the code in master branch. @mikehearn Can you please add more details to the issue along with the FXML being created by SB?

**Comment by mikehearn** [comment] 2019-01-31 16:04
I'll try on master at some point.

**Comment by jperedadnr** [comment] 2019-05-02 15:42
I'm closing this issue as there are not enough info to reproduce it.

**Closed by jperedadnr** 2019-05-02 15:42 UTC
Labels: bug
