### ISSUE TITLE
Windows are not opened in any KDE distro

### ISSUE THREAD

**Issue by milden6** [gluonhq/scenebuilder#292] opened 2020-11-07 22:10 UTC
Also this bug exist in IntelliJ Idea when I run app which built with JavaFX
JavaFX version: 11.0.2
Scene builder version: 11
I have tested this on Manjaro KDE v.20, Kubuntu KDE v.20 on a different laptops

![2020-11-08_01-02](https://user-images.githubusercontent.com/39964648/98452221-5b757980-215e-11eb-8570-4dfbfdb156dd.png)
![2020-11-08_01-03](https://user-images.githubusercontent.com/39964648/98452222-5d3f3d00-215e-11eb-9f7d-ad8825a4c0c8.png)

**Comment by abhinayagarwal** [comment] 2020-12-01 14:27
Seems to be related to https://bugs.openjdk.java.net/browse/JDK-8179073

**Comment by johanvos** [comment] 2020-12-01 20:40
@abhinayagarwal  does that mean you can reproduce https://bugs.openjdk.java.net/browse/JDK-8179073 ? 
The last message there seems to indicate it can't be reproduced, hence it's not active.

**Comment by abhinayagarwal** [comment] 2020-12-02 08:24
Yes, I can. I installed KDE plasma on Ubuntu 20.04 and the issue is reproducible. 

However, the issue is non-existent on default Gnome desktop.

**Comment by abhinayagarwal** [comment] 2020-12-04 09:16
Looks like I spoke too soon. This issue is specific to "Preferences" window and I couldn't recreate it with any other window, except one: Alert Windows shown while closing Scene Builder without saving the document. Both `PreferencesWindowController` and `AlertDialog` sets `setResizable` to `false` on their Stage and this _might be_ to be a cause of the problem.

Having said that, the issue is reproducible with JavaFX 11 and 12 only. The same cannot be reproduced with JavaFX 13 and later. I guess it must have been resolved by one of the ['window-toolkit' fixes which went into JavaFX 13](https://github.com/openjdk/jfx/blob/master/doc-files/release-notes-13.md).

@milden6 Can you run Scene Builder from source with JavaFX 13(or later) and confirm if the issue is resolved?

**Comment by milden6** [comment] 2020-12-04 21:14
@abhinayagarwal Hi! Sorry, I can't. I leave to Windows(all works great) and I don't have any laptop with Linux to check it
Thanks for your reply, the issue can be close

**Closed** 2020-12-07 07:04 UTC
