### ISSUE TITLE
copy and paste text turns out duplicated

### ISSUE THREAD

**Issue by swiftech** [gluonhq/scenebuilder#365] opened 2021-06-05 10:06 UTC
Text copy and paste to any property's input box will be duplicated.
and sadly, I can't select the redundant part of the text by mouse selection to delete it,  it seems that the best way to input something is typing.

### Expected Behavior
It should be exactly what I copy to the clipboard.

### Current Behavior
text is duplicated.

### Steps to Reproduce
select any text from anywhere,
ctrl+c
focus any property input box in scenebuilder
ctrl+v

### Your Environment
MacOS Catalina 10.15.7
Scene Builder 16.0.0

### Screenshots
<img width="320" alt="Screen Shot 2021-06-05 at 5 54 57 PM" src="https://user-images.githubusercontent.com/3277107/120887749-40e97d00-c627-11eb-9a80-afd883ae6654.png">

**Comment by abhinayagarwal** [comment] 2021-07-08 12:08
Duplicate of #263

**Closed by abhinayagarwal** 2021-07-08 12:08 UTC
Labels: bug
