### ISSUE TITLE
SceneBuilder crashes

### ISSUE THREAD

**Issue by palexdev** [gluonhq/scenebuilder#366] opened 2021-06-13 10:56 UTC
Windows 10 20H2 x64, SceneBuilder 16
For some unknown reason, it now crashes when I delete a node, or I do 'CTRL+Z'
And of course there is no log, I wonder why you added this text:
```
Logging
The default configuration stores logging output in a file named scenebuilder-16.0.0.log (possibly followed by a trailing '.' and a digit).
The default file path is C:\Users\thund\AppData\Local\Temp\scenebuilder-16.0.0.log

```
I have never ever seen a log there from SceneBuilder, never

**Comment by ennerf** [comment] 2021-07-07 11:15
I just upgraded to the same setup and I'm running into crashes as well. Trying to run it from commandline yields:

```shell
<...\AppData\Local\SceneBuilder>runtime\bin\java -version
<JAVA_HOME>/lib/ext exists, extensions mechanism no longer supported; Use -classpath instead.
.Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

Renaming the `runtime\lib\ext` directory to `ext2` makes both `java` and `SceneBuilder.exe` execute:

```shell
<...\AppData\Local\SceneBuilder>runtime\bin\java -version
openjdk version "16" 2021-03-16
OpenJDK Runtime Environment AdoptOpenJDK (build 16+36)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 16+36, mixed mode)
```

I also added the renamed directory to the classpath via editing the `SceneBuilder.cfg` file:

```shell
app.classpath=$APPDIR\scenebuilder-16.0.0-all.jar;$APPDIR\..\runtime\lib\ext2\*
```

It's hard to verify whether the classpath works properly, but this runs and I haven't run into any errors yet.

**Comment by abhinayagarwal** [comment] 2021-07-08 04:47
I suspect we need to fix the logging system in Scene Builder. @palexdev would it be possible for you to run Scene Builder from source (instructions are in the Readme) and check what's the root cause of the exception?

**Comment by palexdev** [comment] 2021-07-08 05:23
Unfortunately not anymore
What I did was just restart Windows and since then it didn't happen anymore, so I can't reproduce the issue

**Comment by abhinayagarwal** [comment] 2021-07-08 05:26
In that case, I am going to close this issue. If you face this issue in the future, kindly try and run the application from source. In the meantime, I will log an issue to fix the logging system.

**Closed by abhinayagarwal** 2021-07-08 05:26 UTC
Labels: bug
